### ISSUE TITLE
4 step model 

### ISSUE THREAD

**Issue by orlandoandradeb** [systragroup/quetzal#33]
Hi 
I would like to build a 4 step model in python. I find this library but I find it kind of confuse the documentation. Im not sure that this contains functions realted to  the 4 step model or other demand model. 

Can you help me to know this ? 

Thank you

**Comment by qchasserieau** [comment]
Hello,
**Quetzal contains functions to build a 4 step model.** 
It is its main purpose.

You can find a paper and a recorded presentation presenting the library in 2019 here: 
https://aetransport.org/past-etc-papers/search-all-etc-conference-papers?abstractId=6311&state=b
It has evolved a little since then but the main purpose remains the same.

You can find an example of model built with Quetzal here: 
https://github.com/systragroup/quetzal_paris

Kind regards,
Quentin

**Comment by orlandoandradeb** [comment]
Thank you Quentin !
