### ISSUE TITLE
Assignment Loop

### ISSUE THREAD

**Issue by ha-mish** [systragroup/quetzal#39]
Hello, 
I'm having trouble with the road_pathfinder module, I'm calling the step_road_pathfinder function as follows:
model.step_road_pathfinder(maxiters=15, log=True, speedup=True, tolerance=0.001), but find that in some cases when the volume moved is 0% in the algorithm but the relative gap is above the tolerance the loop fails to exit. 

It prints 'fin: 0' as per line 25 of road_pathfinder but doesn't print the relative gap or exit the function. 

I can get the loop to exit if I relax the parameters (tolerance = 0.01 or maxiters = 5) but would prefer it to reach a higher convergence state. 

Have you experienced this behaviour before or am I calling the assignment process in the wrong way? 

Any help would be much appreciated. 
Hamish

**Comment by qchasserieau** [comment]
Hi,
If it works with a greater tolerance, I'd say that you are doing it right.
The car assignment method is base on the method of successive averages. It is implemented with phi = 2/(2+n) scale. The speedup parameter changes the phi estimation in order to speedup the convergence with frank wolfe algorithm. In your case, it seems to lead to the issue (and this implementation of Frank Wolfe is not great anyway)

**TRY IT WITH speedup=False**

Kind Regards,
Quentin

**Comment by ha-mish** [comment]
Thanks for getting back to me. Speedup = false works, but I'd like the keep the fast version so I ended up putting in an if statement within frank_wolfe that skips appending car_los when the algorithm ends due to phi == 0.

I'll try and work out how to send a merge request to you with the update, but in the meantime I want to do some more testing to make sure it works correctly.
